// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDeleter is an autogenerated mock type for the IDeleter type
type IDeleter struct {
	mock.Mock
}
