// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSurgeryDiagnoses(t *testing.T) {
	t.Parallel()

	query := SurgeryDiagnoses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSurgeryDiagnosesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSurgeryDiagnosesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SurgeryDiagnoses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSurgeryDiagnosesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SurgeryDiagnosisSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSurgeryDiagnosesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SurgeryDiagnosisExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SurgeryDiagnosis exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SurgeryDiagnosisExists to return true, but got false.")
	}
}

func testSurgeryDiagnosesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	surgeryDiagnosisFound, err := FindSurgeryDiagnosis(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if surgeryDiagnosisFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSurgeryDiagnosesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SurgeryDiagnoses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSurgeryDiagnosesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SurgeryDiagnoses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSurgeryDiagnosesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	surgeryDiagnosisOne := &SurgeryDiagnosis{}
	surgeryDiagnosisTwo := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, surgeryDiagnosisOne, surgeryDiagnosisDBTypes, false, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}
	if err = randomize.Struct(seed, surgeryDiagnosisTwo, surgeryDiagnosisDBTypes, false, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = surgeryDiagnosisOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = surgeryDiagnosisTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SurgeryDiagnoses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSurgeryDiagnosesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	surgeryDiagnosisOne := &SurgeryDiagnosis{}
	surgeryDiagnosisTwo := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, surgeryDiagnosisOne, surgeryDiagnosisDBTypes, false, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}
	if err = randomize.Struct(seed, surgeryDiagnosisTwo, surgeryDiagnosisDBTypes, false, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = surgeryDiagnosisOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = surgeryDiagnosisTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func surgeryDiagnosisBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func surgeryDiagnosisAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SurgeryDiagnosis) error {
	*o = SurgeryDiagnosis{}
	return nil
}

func testSurgeryDiagnosesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SurgeryDiagnosis{}
	o := &SurgeryDiagnosis{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis object: %s", err)
	}

	AddSurgeryDiagnosisHook(boil.BeforeInsertHook, surgeryDiagnosisBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisBeforeInsertHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.AfterInsertHook, surgeryDiagnosisAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisAfterInsertHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.AfterSelectHook, surgeryDiagnosisAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisAfterSelectHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.BeforeUpdateHook, surgeryDiagnosisBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisBeforeUpdateHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.AfterUpdateHook, surgeryDiagnosisAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisAfterUpdateHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.BeforeDeleteHook, surgeryDiagnosisBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisBeforeDeleteHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.AfterDeleteHook, surgeryDiagnosisAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisAfterDeleteHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.BeforeUpsertHook, surgeryDiagnosisBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisBeforeUpsertHooks = []SurgeryDiagnosisHook{}

	AddSurgeryDiagnosisHook(boil.AfterUpsertHook, surgeryDiagnosisAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	surgeryDiagnosisAfterUpsertHooks = []SurgeryDiagnosisHook{}
}

func testSurgeryDiagnosesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSurgeryDiagnosesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(surgeryDiagnosisColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSurgeryDiagnosisToManyDiagnoseSurgeries(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SurgeryDiagnosis
	var b, c Surgery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, surgeryDBTypes, false, surgeryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, surgeryDBTypes, false, surgeryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.DiagnoseID = a.ID
	c.DiagnoseID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.DiagnoseSurgeries().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.DiagnoseID == b.DiagnoseID {
			bFound = true
		}
		if v.DiagnoseID == c.DiagnoseID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SurgeryDiagnosisSlice{&a}
	if err = a.L.LoadDiagnoseSurgeries(ctx, tx, false, (*[]*SurgeryDiagnosis)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DiagnoseSurgeries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.DiagnoseSurgeries = nil
	if err = a.L.LoadDiagnoseSurgeries(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DiagnoseSurgeries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSurgeryDiagnosisToManyAddOpDiagnoseSurgeries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SurgeryDiagnosis
	var b, c, d, e Surgery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, surgeryDiagnosisDBTypes, false, strmangle.SetComplement(surgeryDiagnosisPrimaryKeyColumns, surgeryDiagnosisColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Surgery{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, surgeryDBTypes, false, strmangle.SetComplement(surgeryPrimaryKeyColumns, surgeryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Surgery{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDiagnoseSurgeries(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.DiagnoseID {
			t.Error("foreign key was wrong value", a.ID, first.DiagnoseID)
		}
		if a.ID != second.DiagnoseID {
			t.Error("foreign key was wrong value", a.ID, second.DiagnoseID)
		}

		if first.R.Diagnose != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Diagnose != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.DiagnoseSurgeries[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.DiagnoseSurgeries[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.DiagnoseSurgeries().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSurgeryDiagnosesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSurgeryDiagnosesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SurgeryDiagnosisSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSurgeryDiagnosesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SurgeryDiagnoses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	surgeryDiagnosisDBTypes = map[string]string{`ID`: `uuid`, `Bodypart`: `character varying`, `DiagnoseName`: `character varying`, `DiagnoseCode`: `character varying`, `ExtraCode`: `character varying`}
	_                       = bytes.MinRead
)

func testSurgeryDiagnosesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(surgeryDiagnosisPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(surgeryDiagnosisAllColumns) == len(surgeryDiagnosisPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSurgeryDiagnosesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(surgeryDiagnosisAllColumns) == len(surgeryDiagnosisPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SurgeryDiagnosis{}
	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, surgeryDiagnosisDBTypes, true, surgeryDiagnosisPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(surgeryDiagnosisAllColumns, surgeryDiagnosisPrimaryKeyColumns) {
		fields = surgeryDiagnosisAllColumns
	} else {
		fields = strmangle.SetComplement(
			surgeryDiagnosisAllColumns,
			surgeryDiagnosisPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SurgeryDiagnosisSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSurgeryDiagnosesUpsert(t *testing.T) {
	t.Parallel()

	if len(surgeryDiagnosisAllColumns) == len(surgeryDiagnosisPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SurgeryDiagnosis{}
	if err = randomize.Struct(seed, &o, surgeryDiagnosisDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SurgeryDiagnosis: %s", err)
	}

	count, err := SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, surgeryDiagnosisDBTypes, false, surgeryDiagnosisPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SurgeryDiagnosis struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SurgeryDiagnosis: %s", err)
	}

	count, err = SurgeryDiagnoses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
